name: 'Setup Proxer'
description: 'Standard checkout and setup for Proxer'
inputs:
  node-version:
    description: 'Node version to use'
    default: '24'
  install:
    description: 'Whether to run pnpm install'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Prepare pnpm
      run: corepack prepare pnpm@11.10.0 --activate
      shell: bash

    - name: Install dependencies (Windows)
      if: inputs.install == 'true' && runner.os == 'Windows'
      run: pnpm install --frozen-lockfile
      shell: powershell

    - name: Install dependencies (Non-Windows)
      if: inputs.install == 'true' && runner.os != 'Windows'
      run: pnpm install --frozen-lockfile
      shell: bash
