name: 'Setup Proxer'
description: 'Standard checkout and setup for Proxer'
inputs:
  node-version:
    description: 'Node version to use'
    default: '24'
  install:
    description: 'Whether to run pnpm install'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies (Windows)
      if: inputs.install == 'true' && runner.os == 'Windows'
      run: pnpm install --frozen-lockfile
      shell: powershell

    - name: Install dependencies (Non-Windows)
      if: inputs.install == 'true' && runner.os != 'Windows'
      run: pnpm install --frozen-lockfile
      shell: bash
